DOMAIN = "fm_audio_dsp"
PLATFORMS = ["button"]

CONF_DSP_HOST = "dsp_host"
CONF_DSP_HOSTS = "dsp_hosts"
CONF_DSP_PORT = "dsp_port"
CONF_DSP_PIN = "dsp_pin"
CONF_PRESET_COUNT = "preset_count"
CONF_COMMAND_VALUE = "command_value"
CONF_TIMEOUT = "timeout"
CONF_DELAY = "delay"
CONF_X2_MQTT_TOPIC = "x2_mqtt_topic"
CONF_X2_DEVICE_ID = "x2_device_id"
CONF_X2_KEY_MAP = "x2_key_map"

DEFAULT_PORT = 23
DEFAULT_PRESET_COUNT = 4
DEFAULT_COMMAND_VALUE = 1
DEFAULT_TIMEOUT = 5.0
DEFAULT_DELAY = 0.18
MIN_PRESET_COUNT = 2
MIN_PRESET_NUMBER = 1
MAX_PRESETS = 100

COMMAND_STANDBY = "STANDBY"
COMMAND_WAKE = "WAKE"
COMMAND_LOCATE = "LOCATE"
EXTRA_COMMANDS = [COMMAND_STANDBY, COMMAND_WAKE, COMMAND_LOCATE]
